@startuml
autonumber
actor "Receptionist" as VCR

activate VCR
activate "System"
VCR -> "System" : selects option to register the arrival of an SNS user

"System" --> VCR : requests SNS user's number

VCR -> "System" : types requested data

alt (user exists) is (true) then

alt (user has vaccine scheduled) is (true) then

"System" --> VCR : shows all data and requests confirmation

VCR -> "System" : confirms data

alt (user is in correct vaccination center) is (true) then

"System" --> VCR : informs operation success
else (false)

"System" --> VCR : informs the user is not in the correct vaccination center

end
else (false)

"System" --> VCR : informs the user does not have a vaccine scheduled

end
else (false)

"System" --> VCR : informs the user does not exist

deactivate "System"
end

deactivate VCR

@enduml