@startuml
autonumber

activate Administrator
Administrator -> "System" : Starts specifying a new vaccine and its administration process
activate "System"
"System" --> Administrator : Requests new vaccine data
deactivate "System"

Administrator -> "System" : Types requested data

activate "System"
"System" --> Administrator : Requests administration data
deactivate "System"

Administrator -> "System" : Types requested data
activate "System"
"System" --> Administrator : Shows introduced data and requests a confirmation
deactivate "System"

Administrator -> "System" : Confirms the data
activate "System"
"System" --> Administrator : Informs operation success
deactivate "System"

deactivate Administrator

@enduml