@startuml
autonumber
'hide footbox
actor "Administrator" as ADM

participant "SpecifyNewVaccineAndAdministrationProcessUI" as UI
participant "SpecifyNewVaccineAndAdministrationProcessController" as CTRL
participant "Company" as COM
participant "Vaccine" as VAC
participant "VaccineAdministration" as VACAD

ADM -> UI : Starts specifying a new vaccine and its administration process
UI --> ADM : Requests vaccine data
ADM -> UI : Types new vaccine data
UI -> CTRL : CreateNewVaccine(name, brand, type)
CTRL -> COM : vt = CreateNewVaccine()
CTRL -> COM : vt = ValidateVaccine()
COM -> VAC : CreateNewVaccine()
VAC -> VAC : ValidateVaccine()
|||
UI --> ADM : Requests administration data
ADM -> UI : Types administration data
UI -> CTRL : CreateVaccineAdministration(dosage, number of doses, minimum age group, maximum age group)
CTRL -> COM : CreateVaccineAdministration()
COM -> VAC : CreateVaccineAdministration()
VAC -> VACAD : CreateVaccineAdministration()
VACAD -> VACAD : ValidatesVaccineAdministration()
|||
UI --> ADM : Requests confirmation for all data
ADM -> UI : Confirms all data
UI -> CTRL : Confirms all data
CTRL -> COM : Saves new vaccine and administration process
UI --> ADM : Informs operation success

@enduml