@startuml
'acthors.
skinparam usecase{

BackgroundColor<< SprintB >> BlueViolet

}


:Administrator:
:Nurse:
:Vaccination center Receptionist: as Receptionist
:HealthCare center Receptionist:
:User:
:System:
:Center coordinator:
:Timer/clock:

'User cases.

(UC1 - Schedules vaccination) as (UC1)
(UC2 - Specifies type of vaccine to be administer) as (UC2)
(UC3 - Check vaccination center capacity) as (UC3)
(UC4 - Comfirm the vaccination is schedule and informs the user) as (UC4)
(UC5 - Sends to the user an SMS confirming the vaccination event) as (UC5)
(UC6 - Registers Vaccination Centers) as (UC6)  << SprintB >>
(UC7 - Registers arrival of SNS user) as (UC7)
(UC8 - Confirms information about SNS user) as (UC8)
(UC9 - Check user infor and health condition) as (UC9)
(UC10 - Administrates the vaccine) as (UC10)
(UC11 - Registers vaccination andministration with vaccine type) as (UC11)
(UC12 - Record adverse reactions on the system) as (UC12)
(UC13 - Request EU COVID digital certificate) as (UC13)
(UC14 - Monitor the vaccination process) as (UC14) << SprintB >>
(UC15 - Sends user notification SMS or Email) as (UC15)
(UC16 - Verifies user recovery time is over) as (UC16)
(UC17 - Registers Employees) as (UC17)  << SprintB >>
(UC18 - Specify new vaccine type) as (UC18)  << SprintB >>
(UC19 - Specify a new vaccine and its administration process) as (UC19) << SprintB >>
(UC20 - See statistics and charts) as (UC20) << SprintB >>
(UC21 - Evaluate the performance of vaccination process) as (UC21) << SprintB >>
(UC22 - Generate reports) as (UC22) << SprintB >>
(UC23 - Analyze data from other centers) as (UC23) << SprintB >>




'UC

Left to right direction
User --> (UC1)
:HealthCare center Receptionist: --> (UC1)
User --> (UC2)
Nurse --> (UC2)
System --> (UC3)
System --> (UC4)
System --> (UC5)
Administrator --> (UC6)
Administrator --> (UC17)
Administrator --> (UC18)
Administrator --> (UC19)
Receptionist --> (UC7)
Nurse --> (UC8)
Nurse --> (UC9)
Nurse --> (UC10)
Nurse --> (UC11)
Nurse --> (UC12)
User --> (UC13)
:Center coordinator: --> (UC14)
:Center coordinator: --> (UC20)
:Center coordinator: --> (UC21)
:Center coordinator: --> (UC22)
:Center coordinator: --> (UC23)
:Timer/clock: --> (UC15)
:<<To define>>: --> (UC16)
@enduml