 @startuml
'https://plantuml.com/sequence-diagram

autonumber
actor Administrator
activate Administrator
Administrator -> ":System": Starts the option to visualize the list of employees
activate ":System"
":System" --> Administrator: Requests role of employee to be visualized
deactivate ":System"
Administrator -> ":System": Enters role of employee
activate ":System"
":System" --> Administrator: Shows list of employees
deactivate ":System"
@enduml