@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor Administrator
activate Administrator
Administrator -> ListEmployeesUI : Starts the visualize employees list option
activate ListEmployeesUI
ListEmployeesUI --> Administrator :Requests the role of the employees that wants to be listed
deactivate ListEmployeesUI
Administrator -> ListEmployeesUI: Enters the role of the employees that wants to be listed
activate ListEmployeesUI
ListEmployeesUI -> Company: verifyIfExistsEmployees()
activate Company
Company --> ListEmployeesUI : Returns true or false
deactivate Company

alt verifyIfExistsEmployees() = true
ListEmployeesUI -> Company : getEmployeesList()
activate Company
Company --> ListEmployeesUI : return List of all employees
deactivate Company

loop while index < getEmployeesList().size()
ListEmployeesUI -> ListEmployeesController : getEmployeeWithWantedRole(role, index)
activate ListEmployeesController
ListEmployeesController -> ListEmployees : getEmployeeWithWantedRole(role, index)
activate ListEmployees

ListEmployees -> Company : getEmployee(index)
activate Company
Company --> ListEmployees : Returns employee
deactivate Company

alt employee has the wanted role
ListEmployees --> ListEmployeesController : Returns employee with wanted role
ListEmployeesController --> ListEmployeesUI : Returns employee with wanted role
ListEmployeesUI --> Administrator : Returns employee with wanted role
else employee has not the wanted role
ListEmployees --> ListEmployeesController : Returns null
deactivate ListEmployees
ListEmployeesController --> ListEmployeesUI : Returns null
deactivate ListEmployeesController
ListEmployeesUI --> Administrator : Returns null
end

end

else verifyIfExistsEmployees = false
ListEmployeesUI --> Administrator : message = "There are no employees registered"
deactivate ListEmployeesUI
end









@enduml