@startuml
'https://plantuml.com/sequence-diagram

@startuml
autonumber

actor Administrator
activate Administrator
Administrator -> RegisterVaccinationCenterUI: starts new vaccination center
activate RegisterVaccinationCenterUI
RegisterVaccinationCenterUI --> Administrator: request data(name, address,phone number, e-mail address,\n fax number, website address, opening hours, closing hours,\n slot duration, maximum number of vaccines per slot, Center Coordinator)
deactivate RegisterVaccinationCenterUI
Administrator -> RegisterVaccinationCenterUI: types requested data
activate RegisterVaccinationCenterUI
RegisterVaccinationCenterUI -> RegisterVaccinationCenterController: CreateVaccinationCenter(name, address,phone number, e-mail address,\n fax number, website address, opening hours, closing hours,\n slot duration, maximum number of vaccines per slot, Center Coordinator)
activate RegisterVaccinationCenterController
RegisterVaccinationCenterController -> ":Organization": vc = createVaccinationCenter(name, address,phone number, e-mail address,\n fax number, website address, opening hours, closing hours,\n slot duration, maximum number of vaccines per slot, Center Coordinator)
activate ":Organization"
":Organization" --> ":vc: VaccinationCenter"**: create(name, address,phone number, e-mail address,\n fax number, website address, opening hours, closing hours,\n slot duration, maximum number of vaccines per slot, Center Coordinator)
deactivate ":Organization"
RegisterVaccinationCenterController -> ":Organization" : validateVaccinationCenter(vc)
activate ":Organization"
deactivate ":Organization"
deactivate RegisterVaccinationCenterController
RegisterVaccinationCenterUI --> Administrator: shows the data and requests a confirmation
deactivate RegisterVaccinationCenterUI
Administrator -> RegisterVaccinationCenterUI: confirms the data
activate RegisterVaccinationCenterUI
RegisterVaccinationCenterUI -> RegisterVaccinationCenterController: saveVaccinationCenter()
activate RegisterVaccinationCenterController
RegisterVaccinationCenterController -> ":Organization": saveVaccinationCenter(vc)
activate ":Organization"
":Organization" -> ":Organization": validateVaccinationCenter(vc)
activate ":Organization"
deactivate ":Organization"
":Organization" -> ":Organization": addVaccinationCenter(vc)
activate ":Organization"
deactivate ":Organization"
deactivate ":Organization"
deactivate RegisterVaccinationCenterController
RegisterVaccinationCenterUI -> Administrator: informs operation success
deactivate RegisterVaccinationCenterUI


@enduml


@enduml
