@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor Administrator
activate Administrator
Administrator -> ":System": starts specifying a new Vaccination Center
activate ":System"
":System" --> Administrator: request data(name, address,phone number, e-mail address,\n fax number, website address, opening hours, closing hours,\n slot duration, maximum number of vaccines per slot, Center Coordinator)
deactivate ":System"
Administrator -> ":System": types requested data
activate ":System"
":System" --> Administrator: shows the data and requests a confirmation
deactivate ":System"
Administrator -> ":System": confirms the data
activate ":System"
":System" --> Administrator: informs operation success
deactivate ":System"

@enduml
